---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: weather
  namespace: parks
  labels:
    app.kubernetes.io/name: weather
    app.kubernetes.io/part-of: parks
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: weather
  namespace: parks
  labels:
    app.kubernetes.io/name: weather
    app.kubernetes.io/part-of: parks
spec:
  source:
    type: Git
    git:
      uri: https://github.com/sansow/parks.git
      ref: main
    contextDir: weather-service
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-17:1.18
        namespace: openshift
      env:
        - { name: MAVEN_S2I_GOALS, value: "package -DskipTests" }
  output:
    to:
      kind: ImageStreamTag
      name: weather:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  resources:
    limits:
      memory: 1Gi
